# Messaging configuration for the agent system

# Broker settings
broker_type: kafka  # kafka or amqp
broker_url: localhost:9092

# Default queue settings
default_delivery_mode: at_least_once
default_max_retries: 3
default_retry_delay_ms: 1000
default_batch_size: 1
default_poll_timeout_ms: 1000

# Dead letter queue settings
enable_dead_letter: true
dead_letter_suffix: .deadletter

# Consumer groups
request_planner_group: request-planner-group
code_planner_group: code-planner-group
coding_agent_group: coding-agent-group

# Kafka-specific settings
kafka_compression: lz4
kafka_batch_size: 16384
kafka_linger_ms: 10

# AMQP-specific settings (if using RabbitMQ)
amqp_exchange: agent-exchange
amqp_exchange_type: topic
amqp_prefetch_count: 10

# Topic configurations
topics:
  # Request Planner
  plan.in:
    partitions: 3
    replication_factor: 1  # Set to 1 for local development
    retention_ms: 604800000  # 7 days
  
  plan.out:
    partitions: 3
    replication_factor: 1
  
  plan.deadletter:
    partitions: 1
    replication_factor: 1
    retention_ms: 2592000000  # 30 days
  
  # Code Planner
  code.plan.in:
    partitions: 3
    replication_factor: 1
  
  code.plan.out:
    partitions: 3
    replication_factor: 1
  
  # Coding Agent
  coding.task.in:
    partitions: 6
    replication_factor: 1
  
  coding.result.out:
    partitions: 3
    replication_factor: 1
  
  # Build/Test
  build.report:
    partitions: 3
    replication_factor: 1
    retention_ms: 1209600000  # 14 days
  
  test.spec.in:
    partitions: 3
    replication_factor: 1
  
  # Verifier
  regression.alert:
    partitions: 1
    replication_factor: 1
    retention_ms: 2592000000  # 30 days
  
  # Observability
  agent.events:
    partitions: 6
    replication_factor: 1
    retention_ms: 259200000  # 3 days